```{r}
library(rio)
library(dplyr)
library(stringr)
library(tidyr)
```

# 1. Elecciones Generales 2021
## 1.1. Presidenciales

Link: <https://datosabiertos.gob.pe/dataset/resultados-por-mesa-de-las-elecciones-presidenciales-2021-primera-vuelta-oficina-nacional-de>

```{r}
EG2021 <- import("/Users/alexander/Documents/boyco-benites/data/raw/Resultados_1ra_vuelta_Version_PCM.csv")

# Step 2: Set correct column names (omit the last empty column)
correct_names <- c(
  "UBIGEO", "DEPARTAMENTO", "PROVINCIA", "DISTRITO", "TIPO_ELECCION",
  "MESA_DE_VOTACION", "DESCRIP_ESTADO_ACTA", "TIPO_OBSERVACION", "N_CVAS",
  "N_ELEC_HABIL", "VOTOS_P1", "VOTOS_P2", "VOTOS_P3", "VOTOS_P4", "VOTOS_P5",
  "VOTOS_P6", "VOTOS_P7", "VOTOS_P8", "VOTOS_P9", "VOTOS_P10", "VOTOS_P11",
  "VOTOS_P12", "VOTOS_P13", "VOTOS_P14", "VOTOS_P15", "VOTOS_P16", "VOTOS_P17",
  "VOTOS_P18", "VOTOS_VB", "VOTOS_VN", "VOTOS_VI"
)

# Step 3: Drop the last column (which is empty)
EG2021 <- EG2021[, 1:31]

# Step 4: Apply the correct names
names(EG2021) <- correct_names
```

```{r}
# Selected cols: Null and blank votes
dataEG21 <- EG2021 %>% select(1:4,9,10,29,30) %>% # Only relevant features
  group_by(UBIGEO,DEPARTAMENTO, PROVINCIA, DISTRITO) %>%  # Group and sum by district
   summarise(across(where(is.numeric), \(x) sum(x, na.rm = TRUE)), .groups = "drop") %>%
      # Adding zeros:
      mutate(UBIGEO = ifelse(nchar(UBIGEO) == 5, str_pad(UBIGEO, 6, pad = "0"), UBIGEO))

# Changing col names
colnames(dataEG21) <- c("UBIGEO", "DEPARTAMENTO", "PROVINCIA", "DISTRITO", "TOTAL_VOTOS",
                        "ELECTORES_HAB","V_BLANCOS","V_NULOS")
```

```{r}
# Calculating frequencies based on total registered votes
dataEG21$AUSENTISMO <- 1-round(dataEG21$TOTAL_VOTOS/dataEG21$ELECTORES_HAB,2) # Turnout
dataEG21$FreqBLANCOS <- round(dataEG21$V_BLANCOS/dataEG21$TOTAL_VOTOS,2) # Blank votes
dataEG21$FreqNULOS <- round(dataEG21$V_NULOS/dataEG21$TOTAL_VOTOS,2) # Null votes
dataEG21$FreqINVALIDOS = dataEG21$FreqBLANCOS + dataEG21$FreqNULOS # Invalid votes

# Last steps:
dataEG21$YEAR = 2021
dataEG21$TYPE = "PRESIDENCIAL"
```


1.2. Congresales

Link: <https://datosabiertos.gob.pe/dataset/resultados-por-mesa-de-las-elecciones-congresales-2021-oficina-nacional-de-procesos>

```{r}
EG2021C <- import("/Users/alexander/Documents/boyco-benites/data/raw/EG2021_Congresal.csv")
```

```{r}
# Separate total number of electors and total number of votes because of complicated data structure
d <- EG2021C %>% 
  select("UBIGEO", "DEPARTAMENTO", "PROVINCIA", "DISTRITO","MESA_DE_VOTACION","N_CVAS",
         "N_ELEC_HABIL") %>% # Adding zeros:
  mutate(UBIGEO = ifelse(nchar(UBIGEO) == 5, str_pad(UBIGEO, 6, pad = "0"), UBIGEO)) %>%
  distinct() # Unique cases
  
d <- d %>% select(-MESA_DE_VOTACION) %>% 
  group_by(UBIGEO,DEPARTAMENTO, PROVINCIA, DISTRITO) %>%  # Group and sum by district
  summarise(across(where(is.numeric), \(x) sum(x, na.rm = TRUE)), .groups = "drop")

# d has both variables for aggregated by district
```

```{r}
dataEG21C <- EG2021C %>% 
  select("UBIGEO", "DEPARTAMENTO", "PROVINCIA", "DISTRITO","DESCRIPCION_OP","N_TOTAL_VOTOS",
         "MESA_DE_VOTACION") %>% 
  # Only relevant categories
  filter(DESCRIPCION_OP %in% c("VOTOS EN BLANCO", "VOTOS NULOS")) %>% 
  # Adding zeros
  mutate(UBIGEO = ifelse(nchar(UBIGEO) == 5, str_pad(UBIGEO, 6, pad = "0"), UBIGEO)) %>%
  # Sum values
  group_by(UBIGEO, DEPARTAMENTO, PROVINCIA, DISTRITO, DESCRIPCION_OP) %>%
  # Data wrangling
  summarise(VOTOS= sum(N_TOTAL_VOTOS, na.rm = TRUE)) %>% 
  pivot_wider(
    names_from = DESCRIPCION_OP,
    values_from = VOTOS)
```

```{r}
# Combine the two tables:
d <- d[,c(1,5,6)] # Avoiding duplication
dataEG21C <- merge(dataEG21C, d, by = "UBIGEO", all.x = TRUE) # Merge

# Changing col names
colnames(dataEG21C) <- c("UBIGEO", "DEPARTAMENTO", "PROVINCIA", "DISTRITO",
                         "V_BLANCOS","V_NULOS","TOTAL_VOTOS","ELECTORES_HAB")
```

```{r}
# Calculations
dataEG21C$AUSENTISMO <- 1 - round(dataEG21C$TOTAL_VOTOS / dataEG21C$ELECTORES_HAB,2) #Turnout
dataEG21C$FreqBLANCOS <- round(dataEG21C$V_BLANCOS / dataEG21C$TOTAL_VOTOS, 2) #Blank
dataEG21C$FreqNULOS <- round(dataEG21C$V_NULOS / dataEG21C$TOTAL_VOTOS, 2) #Null
dataEG21C$FreqINVALIDOS <- dataEG21C$FreqBLANCOS + dataEG21C$FreqNULOS #Invalid

# Last steps:
dataEG21C$YEAR = 2021
dataEG21C$TYPE = "CONGRESAL"
```


# 2. Elecciones Generales 2016
## 2.1. Presidenciales

Link: <https://datosabiertos.gob.pe/dataset/resultados-por-mesa-de-las-elecciones-presidenciales-2016-primera-vuelta-oficina-nacional-de>

```{r}
EG2016 <- import("/Users/alexander/Documents/boyco-benites/data/raw/2016_EG2016_Presidencial.csv")
```

```{r}
dataEG16 <- EG2016 %>% select(1:4,9,10,25,26) %>% # Only relevant features
  group_by(UBIGEO,DEPARTAMENTO, PROVINCIA, DISTRITO) %>%  # Group and sum by district
   summarise(across(where(is.numeric), \(x) sum(x, na.rm = TRUE)), .groups = "drop") %>%
      # Adding zeros:
      mutate(UBIGEO = ifelse(nchar(UBIGEO) == 5, str_pad(UBIGEO, 6, pad = "0"), UBIGEO))

# Changing col names
colnames(dataEG16) <- c("UBIGEO", "DEPARTAMENTO", "PROVINCIA", "DISTRITO", "TOTAL_VOTOS",
                        "ELECTORES_HAB","V_BLANCOS","V_NULOS")
```

```{r}
# Calculating frequencies based on total registered votes
dataEG16$AUSENTISMO <- 1-round(dataEG16$TOTAL_VOTOS / dataEG16$ELECTORES_HAB,2) # Turnout
dataEG16$FreqBLANCOS <- round(dataEG16$V_BLANCOS/dataEG16$TOTAL_VOTOS,2) # Blank votes
dataEG16$FreqNULOS <- round(dataEG16$V_NULOS/dataEG16$TOTAL_VOTOS,2) # Null votes
dataEG16$FreqINVALIDOS = dataEG16$FreqBLANCOS + dataEG16$FreqNULOS # Invalid votes

# Last steps:
dataEG16$YEAR = 2016
dataEG16$TYPE = "PRESIDENCIAL"
```

## 2.2. Congresales

Link: <https://datosabiertos.gob.pe/dataset/resultados-por-mesa-de-las-elecciones-congresales-2016-oficina-nacional-de-procesos-0>

```{r}
EG2016C <- import("/Users/alexander/Documents/boyco-benites/data/raw/2016_EG2016_Congresal.csv")
```

```{r}
# Separate total number of electors and total number of votes because of complicated data structure
d <- EG2016C %>% 
  select("UBIGEO", "DEPARTAMENTO", "PROVINCIA", "DISTRITO","MESA_DE_VOTACION","N_CVAS",
         "N_ELEC_HABIL") %>% # Adding zeros:
  mutate(UBIGEO = ifelse(nchar(UBIGEO) == 5, str_pad(UBIGEO, 6, pad = "0"), UBIGEO)) %>%
  distinct() # Unique cases

d <- d %>% select(-MESA_DE_VOTACION) %>% 
  group_by(UBIGEO,DEPARTAMENTO, PROVINCIA, DISTRITO) %>%  # Group and sum by district
  summarise(across(where(is.numeric), \(x) sum(x, na.rm = TRUE)), .groups = "drop")

# d has both variables for aggregated by district
```

```{r}
dataEG16C <- EG2016C %>% 
  select("UBIGEO", "DEPARTAMENTO", "PROVINCIA", "DISTRITO","DESCRIPCION_OP","N_TOTAL_VOTOS",
         "MESA_DE_VOTACION") %>% 
  # Only relevant categories
  filter(DESCRIPCION_OP %in% c("VOTOS EN BLANCO", "VOTOS NULOS")) %>% 
  # Adding zeros
  mutate(UBIGEO = ifelse(nchar(UBIGEO) == 5, str_pad(UBIGEO, 6, pad = "0"), UBIGEO)) %>%
  # Sum values
  group_by(UBIGEO, DEPARTAMENTO, PROVINCIA, DISTRITO, DESCRIPCION_OP) %>%
  # Data wrangling
  summarise(VOTOS= sum(N_TOTAL_VOTOS, na.rm = TRUE)) %>% 
  pivot_wider(
    names_from = DESCRIPCION_OP,
    values_from = VOTOS)
```

```{r}
# Combine the two tables:
d <- d[,c(1,5,6)] # Avoiding duplication
dataEG16C <- merge(dataEG16C, d, by = "UBIGEO", all.x = TRUE) # Merge

# Changing col names
colnames(dataEG16C) <- c("UBIGEO", "DEPARTAMENTO", "PROVINCIA", "DISTRITO",
                         "V_BLANCOS","V_NULOS","TOTAL_VOTOS","ELECTORES_HAB")
```

```{r}
# Calculations
dataEG16C$AUSENTISMO <- 1 - round(dataEG16C$TOTAL_VOTOS / dataEG16C$ELECTORES_HAB,2) #Turnout
dataEG16C$FreqBLANCOS <- round(dataEG16C$V_BLANCOS / dataEG16C$TOTAL_VOTOS, 2) #Blank
dataEG16C$FreqNULOS <- round(dataEG16C$V_NULOS / dataEG16C$TOTAL_VOTOS, 2) #Null
dataEG16C$FreqINVALIDOS <- dataEG16C$FreqBLANCOS + dataEG16C$FreqNULOS #Invalid

# Last steps:
dataEG16C$YEAR = 2016
dataEG16C$TYPE = "CONGRESAL"
```


# 3. Elecciones Generales 2011
## 3.1. Presidenciales

Link: <https://datosabiertos.gob.pe/dataset/resultados-por-mesa-de-las-elecciones-presidenciales-2011-primera-vuelta-oficina-nacional-0>

```{r}
EG2011 <- import("/Users/alexander/Documents/boyco-benites/data/raw/2011_EG2011_Presidencial.xlsx")
```

```{r}
dataEG11 <- EG2011 %>% select(1:4,9,10,22,23) %>% # Only relevant features
  group_by(UBIGEO,DEPARTAMENTO, PROVINCIA, DISTRITO) %>%  # Group and sum by district
   summarise(across(where(is.numeric), \(x) sum(x, na.rm = TRUE)), .groups = "drop") %>%
      # Adding zeros:
      mutate(UBIGEO = ifelse(nchar(UBIGEO) == 5, str_pad(UBIGEO, 6, pad = "0"), UBIGEO))

# Changing col names
colnames(dataEG11) <- c("UBIGEO", "DEPARTAMENTO", "PROVINCIA", "DISTRITO", "TOTAL_VOTOS",
                        "ELECTORES_HAB","V_BLANCOS","V_NULOS")
```

```{r}
# Calculating frequencies based on total registered votes
dataEG11$AUSENTISMO <- 1-round(dataEG11$TOTAL_VOTOS / dataEG11$ELECTORES_HAB,2) # Turnout
dataEG11$FreqBLANCOS <- round(dataEG11$V_BLANCOS/dataEG11$TOTAL_VOTOS,2) # Blank votes
dataEG11$FreqNULOS <- round(dataEG11$V_NULOS/dataEG11$TOTAL_VOTOS,2) # Null votes
dataEG11$FreqINVALIDOS = dataEG11$FreqBLANCOS + dataEG11$FreqNULOS # Invalid votes

# Last steps:
dataEG11$YEAR = 2011
dataEG11$TYPE = "PRESIDENCIAL"
```

## 3.2. Congresales

Link: <https://datosabiertos.gob.pe/dataset/resultados-por-mesa-de-las-elecciones-congresales-2011-oficina-nacional-de-procesos>

```{r}
EG2011C <- import("/Users/alexander/Documents/boyco-benites/data/raw/2011_EG2011_Congresal.csv")
```

```{r}
# Separate total number of electors and total number of votes because of complicated data structure
d <- EG2011C %>% 
  select("UBIGEO", "DEPARTAMENTO", "PROVINCIA", "DISTRITO","MESA_DE_VOTACION","N_CVAS",
         "N_ELEC_HABIL") %>% # Adding zeros:
  mutate(UBIGEO = ifelse(nchar(UBIGEO) == 5, str_pad(UBIGEO, 6, pad = "0"), UBIGEO)) %>%
  distinct() # Unique cases

d <- d %>% select(-MESA_DE_VOTACION) %>% 
  group_by(UBIGEO,DEPARTAMENTO, PROVINCIA, DISTRITO) %>%  # Group and sum by district
  summarise(across(where(is.numeric), \(x) sum(x, na.rm = TRUE)), .groups = "drop")

# d has both variables for aggregated by district
```

```{r}
dataEG11C <- EG2011C %>% 
  select("UBIGEO", "DEPARTAMENTO", "PROVINCIA", "DISTRITO","DESCRIPCION_OP","N_TOTAL_VOTOS",
         "MESA_DE_VOTACION") %>% 
  # Only relevant categories
  filter(DESCRIPCION_OP %in% c("VOTOS BLANCOS", "VOTOS NULOS")) %>% 
  # Adding zeros
  mutate(UBIGEO = ifelse(nchar(UBIGEO) == 5, str_pad(UBIGEO, 6, pad = "0"), UBIGEO)) %>%
  # Sum values
  group_by(UBIGEO, DEPARTAMENTO, PROVINCIA, DISTRITO, DESCRIPCION_OP) %>%
  # Data wrangling
  summarise(VOTOS= sum(N_TOTAL_VOTOS, na.rm = TRUE)) %>% 
  pivot_wider(
    names_from = DESCRIPCION_OP,
    values_from = VOTOS)
```

```{r}
# Combine the two tables:
d <- d[,c(1,5,6)] # Avoiding duplication
dataEG11C <- merge(dataEG11C, d, by = "UBIGEO", all.x = TRUE) # Merge

# Changing col names
colnames(dataEG11C) <- c("UBIGEO", "DEPARTAMENTO", "PROVINCIA", "DISTRITO",
                         "V_BLANCOS","V_NULOS","TOTAL_VOTOS","ELECTORES_HAB")
```

```{r}
# Calculations
dataEG11C$AUSENTISMO <- 1 - round(dataEG11C$TOTAL_VOTOS / dataEG11C$ELECTORES_HAB,2) #Turnout
dataEG11C$FreqBLANCOS <- round(dataEG11C$V_BLANCOS / dataEG11C$TOTAL_VOTOS, 2) #Blank
dataEG11C$FreqNULOS <- round(dataEG11C$V_NULOS / dataEG11C$TOTAL_VOTOS, 2) #Null
dataEG11C$FreqINVALIDOS <- dataEG11C$FreqBLANCOS + dataEG11C$FreqNULOS #Invalid

# Last steps:
dataEG11C$YEAR = 2011
dataEG11C$TYPE = "CONGRESAL"
```


# 4. Elecciones Generales 2006
## 4.1. Presidenciales

Link: <https://datosabiertos.gob.pe/dataset/resultados-por-mesa-de-las-generales-2006-primera-vuelta-oficina-nacional-de-procesos>

```{r}
EG2006 <- import("/Users/alexander/Documents/boyco-benites/data/raw/EG2006_Presidencial.csv")
```

```{r}
dataEG06 <- EG2006 %>% select(1:4,9,10,31,32) %>% # Only relevant features
  group_by(UBIGEO,DEPARTAMENTO, PROVINCIA, DISTRITO) %>%  # Group and sum by district
   summarise(across(where(is.numeric), \(x) sum(x, na.rm = TRUE)), .groups = "drop") %>%
      # Adding zeros:
      mutate(UBIGEO = ifelse(nchar(UBIGEO) == 5, str_pad(UBIGEO, 6, pad = "0"), UBIGEO))

# Changing col names
colnames(dataEG06) <- c("UBIGEO", "DEPARTAMENTO", "PROVINCIA", "DISTRITO", "TOTAL_VOTOS",
                        "ELECTORES_HAB","V_BLANCOS","V_NULOS")
```

```{r}
# Calculating frequencies based on total registered votes
dataEG06$AUSENTISMO <- 1-round(dataEG06$TOTAL_VOTOS / dataEG06$ELECTORES_HAB,2) # Turnout
dataEG06$FreqBLANCOS <- round(dataEG06$V_BLANCOS/dataEG06$TOTAL_VOTOS,2) # Blank votes
dataEG06$FreqNULOS <- round(dataEG06$V_NULOS/dataEG06$TOTAL_VOTOS,2) # Null votes
dataEG06$FreqINVALIDOS = dataEG06$FreqBLANCOS + dataEG06$FreqNULOS # Invalid votes

# Last steps:
dataEG06$YEAR = 2006
dataEG06$TYPE = "PRESIDENCIAL"
```


## 4.2. Congresales

Link: <https://datosabiertos.gob.pe/dataset/resultados-por-mesa-de-las-elecciones-congresales-2006-oficina-nacional-de-procesos-0>

```{r}
EG2006C <- import("/Users/alexander/Documents/boyco-benites/data/raw/EG2006_Congresal.csv")
```

```{r}
# Separate total number of electors and total number of votes because of complicated data structure
d <- EG2006C %>% 
  select("UBIGEO", "DEPARTAMENTO", "PROVINCIA", "DISTRITO","MESA_DE_VOTACION","N_CVAS",
         "N_ELEC_HABIL") %>% # Adding zeros:
  mutate(UBIGEO = ifelse(nchar(UBIGEO) == 5, str_pad(UBIGEO, 6, pad = "0"), UBIGEO)) %>%
  distinct() # Unique cases

d <- d %>% select(-MESA_DE_VOTACION) %>% 
  group_by(UBIGEO,DEPARTAMENTO, PROVINCIA, DISTRITO) %>%  # Group and sum by district
  summarise(across(where(is.numeric), \(x) sum(x, na.rm = TRUE)), .groups = "drop")

# d has both variables for aggregated by district
```

```{r}
dataEG06C <- EG2006C %>% 
  select("UBIGEO", "DEPARTAMENTO", "PROVINCIA", "DISTRITO","DESCRIPCION_OP","N_TOTAL_VOTOS",
         "MESA_DE_VOTACION") %>% 
  # Only relevant categories
  filter(DESCRIPCION_OP %in% c("VOTOS BLANCOS", "VOTOS NULOS")) %>% 
  # Adding zeros
  mutate(UBIGEO = ifelse(nchar(UBIGEO) == 5, str_pad(UBIGEO, 6, pad = "0"), UBIGEO)) %>%
  # Sum values
  group_by(UBIGEO, DEPARTAMENTO, PROVINCIA, DISTRITO, DESCRIPCION_OP) %>%
  # Data wrangling
  summarise(VOTOS= sum(N_TOTAL_VOTOS, na.rm = TRUE)) %>% 
  pivot_wider(
    names_from = DESCRIPCION_OP,
    values_from = VOTOS)
```

```{r}
# Combine the two tables:
d <- d[,c(1,5,6)] # Avoiding duplication
dataEG06C <- merge(dataEG06C, d, by = "UBIGEO", all.x = TRUE) # Merge

# Changing col names
colnames(dataEG06C) <- c("UBIGEO", "DEPARTAMENTO", "PROVINCIA", "DISTRITO",
                         "V_BLANCOS","V_NULOS","TOTAL_VOTOS","ELECTORES_HAB")
```

```{r}
# Calculations
dataEG06C$AUSENTISMO <- 1 - round(dataEG06C$TOTAL_VOTOS / dataEG06C$ELECTORES_HAB,2) #Turnout
dataEG06C$FreqBLANCOS <- round(dataEG06C$V_BLANCOS / dataEG06C$TOTAL_VOTOS, 2) #Blank
dataEG06C$FreqNULOS <- round(dataEG06C$V_NULOS / dataEG06C$TOTAL_VOTOS, 2) #Null
dataEG06C$FreqINVALIDOS <- dataEG06C$FreqBLANCOS + dataEG06C$FreqNULOS #Invalid

# Last steps:
dataEG06C$YEAR = 2006
dataEG06C$TYPE = "CONGRESAL"
```


# 5. Elecciones Generales 2001
## 5.1. Presidenciales

Requested directly to ONPE

```{r}
EG2001 <- import("/Users/alexander/Documents/boyco-benites/data/raw/EG2001-Resultados_Presidenciales.xlsx")
```

```{r}
dataEG01 <- EG2001 %>% select(2:7) %>% # Adding zeros: 
  
  filter(`AGRUPACIÓN POLÍTICA` %in% c("ELECTORES HABILES","TOTAL DE VOTOS", "VOTOS BLANCOS","VOTOS NULOS")) %>%
  
  pivot_wider(
    names_from = `AGRUPACIÓN POLÍTICA`,
    values_from = `VOTOS OBTENIDOS`)

names(dataEG01) <- c("UBIGEO","DEPARTAMENTO","PROVINCIA","DISTRITO","V_BLANCOS","V_NULOS",
                     "TOTAL_VOTOS","ELECTORES_HAB")
```

```{r}
# Calculating frequencies based on total registered votes
dataEG01$AUSENTISMO <- 1-round(dataEG01$TOTAL_VOTOS / dataEG01$ELECTORES_HAB,2) # Turnout
dataEG01$FreqBLANCOS <- round(dataEG01$V_BLANCOS/dataEG01$TOTAL_VOTOS,2) # Blank votes
dataEG01$FreqNULOS <- round(dataEG01$V_NULOS/dataEG01$TOTAL_VOTOS,2) # Null votes
dataEG01$FreqINVALIDOS = dataEG01$FreqBLANCOS + dataEG01$FreqNULOS # Invalid votes

# Last steps:
dataEG01$YEAR = 2001
dataEG01$TYPE = "PRESIDENCIAL"

dataEG01 <- dataEG01[, names(dataEG06)]
```



## 5.2. Congresales

Requested





## Rbind:

```{r}
# Presidenciales
dataEGP = rbind(dataEG01, dataEG06)
dataEGP = rbind(dataEGP, dataEG11)
dataEGP = rbind(dataEGP, dataEG16)
dataEGP = rbind(dataEGP, dataEG21)
```


